/**
 * The "build" for a frontend that has no build.
 *
 * There is nothing to compile: `public/` is plain HTML, CSS and ES modules the
 * browser runs as written. What this does instead is the part a build would
 * otherwise do for free — check that every file the pages reference exists, and
 * that each module parses. A missing `<script src>` is a blank page, and a syntax
 * error in a module is a blank page, and both are exactly the failure a demo
 * cannot survive.
 *
 *   node build.mjs           # check, then report
 *   node build.mjs --check   # identical; the workspace `typecheck` script
 *
 * Exits non-zero on any problem, so `npm run build --workspaces` fails loudly
 * rather than reporting success for a page that will not load.
 */

import { spawnSync } from 'node:child_process';
import { readdirSync, readFileSync, existsSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, 'public');
const problems = [];

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(path));
    else out.push(path);
  }
  return out;
}

if (!existsSync(ROOT)) {
  console.error(`No public/ directory at ${ROOT}`);
  process.exit(1);
}

const files = walk(ROOT);
const relative = (path) => path.slice(ROOT.length + 1).replace(/\\/g, '/');

// --- every referenced local asset exists ------------------------------------

for (const file of files.filter((path) => path.endsWith('.html'))) {
  const html = readFileSync(file, 'utf8');
  for (const match of html.matchAll(/(?:src|href)="([^"]+)"/g)) {
    const reference = match[1];
    // Absolute URLs and the server's generated /config.js are not files here.
    if (/^(https?:)?\/\//.test(reference) || reference.startsWith('#')) continue;
    if (reference === '/config.js') continue;

    const target = join(ROOT, reference.replace(/^\//, '').split('?')[0]);
    if (!existsSync(target)) {
      problems.push(`${relative(file)} references ${reference}, which does not exist`);
    }
  }
}

// --- every module parses -----------------------------------------------------
//
// `node --check` treats a .mjs file as an ES module and parses it without
// running it, which is exactly what is wanted: no DOM, no side effects, and a
// syntax error reported with a line number.

for (const file of files.filter((path) => path.endsWith('.mjs'))) {
  const result = spawnSync(process.execPath, ['--check', file], { encoding: 'utf8' });
  if (result.status !== 0) {
    problems.push(`${relative(file)}: ${(result.stderr ?? '').trim().split('\n').slice(0, 3).join(' ')}`);
  }
}

// --- generate config.js ------------------------------------------------------
//
// `server.mjs` serves this dynamically for local development, but a static host
// (Vercel, Netlify, S3) has no server to do that — so the build writes it.
//
// It carries one value: which backend the page talks to. It is generated rather
// than committed because it differs per deployment, and it holds **no secret** —
// everything in it is visible to anyone who opens the page, which is why the API
// base is the only thing allowed here.
const apiBase = process.env.WEB_API_BASE ?? 'http://127.0.0.1:8080';
writeFileSync(
  join(ROOT, 'config.js'),
  `// Generated by build.mjs. Do not edit; set WEB_API_BASE instead.\n` +
    `window.COVENANT_API_BASE = ${JSON.stringify(apiBase)};\n`,
  'utf8',
);

if (problems.length > 0) {
  console.error('web check failed:');
  for (const problem of problems) console.error(`  ${problem}`);
  process.exit(1);
}

console.log(`web check passed — ${files.length} file(s) in public/`);
console.log(`config.js  →  API base ${apiBase}`);
if (apiBase.includes('127.0.0.1') || apiBase.includes('localhost')) {
  console.log(
    '\nNOTE: the API base points at localhost. A page served from a public URL\n' +
      '      cannot reach that. Set WEB_API_BASE to a publicly reachable backend.',
  );
}
